const UA={'user-agent':'JoesTrafficScope/1.3H-R','accept':'application/json'};
const TIMEOUT_MS=6500;
const CACHE_TTL_MS=3*60*60*1000;
const memCache=new Map();
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=300','netlify-cdn-cache-control':'public, durable, s-maxage=10800, stale-while-revalidate=86400'}})}
function clean(v,max=24){return String(v||'').trim().toUpperCase().replace(/[^A-Z0-9+.-]/g,'').slice(0,max)}
async function fetchJson(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{headers:UA,signal:c.signal});const text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch{throw new Error(`HTTP ${r.status} invalid JSON`)}return {ok:r.ok,status:r.status,data:d}}finally{clearTimeout(t)}}
function airport(x){if(!x||typeof x!=='object')return null;const iata=String(x.iata_code||'').trim().toUpperCase(),icao=String(x.icao_code||'').trim().toUpperCase();return {iata,icao,display:iata||icao||'',name:String(x.name||''),municipality:String(x.municipality||''),country:String(x.country_name||''),country_iso:String(x.country_iso_name||''),latitude:Number.isFinite(+x.latitude)?+x.latitude:null,longitude:Number.isFinite(+x.longitude)?+x.longitude:null}}
function normalize(response,callsign,hex){const root=response?.response||{},fr=root.flightroute||null,ac=root.aircraft||null,origin=airport(fr?.origin),destination=airport(fr?.destination),route=origin?.display&&destination?.display?`${origin.display} → ${destination.display}`:'',airline=fr?.airline&&typeof fr.airline==='object'?{name:String(fr.airline.name||''),icao:String(fr.airline.icao||''),iata:String(fr.airline.iata||''),country:String(fr.airline.country||'')}:null,aircraft=ac?{type:String(ac.type||''),icao_type:String(ac.icao_type||''),manufacturer:String(ac.manufacturer||''),registration:String(ac.registration||''),owner:String(ac.registered_owner||''),photo:ac.url_photo||null,thumbnail:ac.url_photo_thumbnail||null}:null;return {found:!!(fr||ac),source:'ADSBDB',callsign,hex,route,origin,destination,airline,aircraft}}
export default async(req)=>{try{const u=new URL(req.url),callsign=clean(u.searchParams.get('callsign')),hex=clean(u.searchParams.get('hex'),12);if(!callsign&&!hex)return json({error:'hex or callsign required'},400);const key=`${hex}|${callsign}`,hit=memCache.get(key);if(hit&&Date.now()-hit.t<CACHE_TTL_MS)return json(hit.data);let url;if(hex&&callsign)url=`https://api.adsbdb.com/v0/aircraft/${encodeURIComponent(hex)}?callsign=${encodeURIComponent(callsign)}`;else if(hex)url=`https://api.adsbdb.com/v0/aircraft/${encodeURIComponent(hex)}`;else url=`https://api.adsbdb.com/v0/callsign/${encodeURIComponent(callsign)}`;const r=await fetchJson(url);if(r.status===404){if(hex&&callsign){const rr=await fetchJson(`https://api.adsbdb.com/v0/callsign/${encodeURIComponent(callsign)}`);if(rr.ok){const out=normalize(rr.data,callsign,hex);memCache.set(key,{t:Date.now(),data:out});return json(out)}}const out={found:false,source:'ADSBDB',callsign,hex,route:'',origin:null,destination:null,airline:null,aircraft:null};memCache.set(key,{t:Date.now(),data:out});return json(out)}if(!r.ok)return json({error:`ADSBdb HTTP ${r.status}`,source:'ADSBDB'},502);const out=normalize(r.data,callsign,hex);memCache.set(key,{t:Date.now(),data:out});if(memCache.size>500)memCache.delete(memCache.keys().next().value);return json(out)}catch(e){return json({error:String(e?.message||e),source:'ADSBDB'},502)}};
export const config={path:'/api/enrich'};
